### ISSUE TITLE
Different results from other color blindness simulator

### ISSUE THREAD

**Issue by hmicn** [joergdietrich/daltonize#13]
Hello,

This script gives me different results from other color blindness simulator.

Steps to reproduce:
1. Select an image
2. Simulate color blindness with t, d or p
3. Compare the results with https://www.color-blindness.com/coblis-color-blindness-simulator/ or https://logolab.app/lab

Expectation:
The results are the same

Actual:
The results are very different

Data image used:

![foreground_with_background](https://user-images.githubusercontent.com/6259821/75624465-99280880-5bb4-11ea-8dd2-a0ea8d1bd7b2.png)

**Comment by joergdietrich** [comment]
Thank you for reporting this. I will need to verify the transformation matrices based on this explanation: https://ixora.io/projects/colorblindness/color-blindness-simulation-research/ (URL added mostly for my own reference).

**Comment by couriersud** [comment]
I am not a python expert but the code doesn't seem to convert srgb to linear rgb and back. Another source may be png/jpg formats and their gamma interpretation in viewers like eog.

**Comment by hmicn** [comment]
The gamma might be something to explore and regarding the rgb conversion, I think it's ok:
```
lms = transform_colorspace(rgb, rgb2lms)
# Calculate image as seen by the color blind
sim_lms = transform_colorspace(lms, cb_matrices[color_deficit])
# Transform back to RBG
sim_rgb = transform_colorspace(sim_lms, lms2rgb)

```
