### ISSUE TITLE
Broken simulation and daltonization with np.float16 and numpy >= 1.21.0

### ISSUE THREAD

**Issue by nburrus** [joergdietrich/daltonize#18]
On my Ubuntu 20.04 with Python 3.8.10 and numpy 1.21.3 I always get black images out of the `simulation` function (all values are zero). numpy 1.20.3 works fine, the problem started with numpy 1.21.0.

The guilty part is `transform_colorspace`, where the `np.einsum("ij, ...j", mat, img, dtype=np.float16, casting="same_kind")` always returns 0 when given rgb2lms as input, unless `dtype` is changed back to `np.float32`. As a consequence this also breaks the daltonization, which becomes a noop.

I'm not sure if this is actually a numpy bug, but an alternative solution is to return `img @ mat.T`, which is equivalent to the `einsum` thanks to numpy broadcasting rules, but still works with float16. It may also be a bit faster.

Going back to float32 might be a safer choice too!

**Comment by joergdietrich** [comment]
Thanks for reporting this. This definitely looks like a numpy bug to me. I'll file a report over there. The matrix multiplication is indeed about 30% faster. Going back to float32 will again limit the image sizes daltonize can handle. See #14 .

So I'll use the @ operator instead.

**Comment by joergdietrich** [comment]
Bug filed against numpy: https://github.com/numpy/numpy/issues/20305
