### ISSUE TITLE
Einstein sum error

### ISSUE THREAD

**Issue by r-barnes** [joergdietrich/daltonize#7]
I get the following error when I run the program on a 800x600 PNG image:

```
ValueError: operand 0 did not have enough dimensions to match the broadcasting, and couldn't be extended because einstein sum subscripts were specified at both the start and end
```

**Comment by joergdietrich** [comment]
Sorry for the slow response. I was on extended leave.

I'm not able to reproduce the problem you describe. How exactly do you call the program? Can you provide an example image that fails?

**Comment by r-barnes** [comment]
No worries.

I am running:

```
./daltonize.py -s -t d ../in.jpg ./out.jpg
```

on the following image:

![in](https://cloud.githubusercontent.com/assets/3118036/11919414/fa37dc02-a706-11e5-8bad-931747883621.jpg)

I've also tried the image as a PNG.

The full error is:

```
Traceback (most recent call last):
  File "./daltonize.py", line 478, in <module>
    simul_rgb = simulate(orig_img, args.type)
  File "./daltonize.py", line 78, in simulate
    lms = transform_colorspace(rgb, rgb2lms)
  File "./daltonize.py", line 40, in transform_colorspace
    return np.einsum("ij, ...j", mat, img)
ValueError: operand 0 did not have enough dimensions to match the broadcasting, and couldn't be extended because einstein sum subscripts were specified at both the start and end
```

**Comment by joergdietrich** [comment]
This works here with numpy-1.9.3. Which version do you use?

**Comment by r-barnes** [comment]
I'm on 1.8.2, so maybe that is the issue.

**Comment by r-barnes** [comment]
Yup, upgrading to 1.10.2 fixed it.

**Comment by joergdietrich** [comment]
Thanks. I'll put a requirement numpy>=1.9.x in.
